### ISSUE TITLE
Feedback on UI

### ISSUE THREAD

**Issue by Kiv** [mrpandey/d3graphTheory#1]
Hi, first off thanks for making this, it's very cool :) 

I had a lot of difficulty with the UI during the course, and I thought you might want to hear about some ideas to improve. I'm not sure if your goal for this project is to teach as many people as possible, or just to play around with D3 but if the goal is to teach, then I think fixing the below issues would help reach a wider audience.

1) Clicking on graph edges is very difficult because they are so thin. It requires a precise motion that is hard on a trackpad and hard for people that don't use computers all the time. It's very frustrating if you click near an edge, and instead it just creates a new vertex that you don't want.

2) It's preferable to not require right-clicking in an interface. I know my parents who are an 'average Joe' user don't understand what right clicking is and would be unable to do the course for that reason. Better would be either a "trashcan" area where you can drag a node that you don't want, or clicking a node to select it and then pressing a key like X to delete it.

3) On the challenges, when you complete one it automatically and rapidly advances to the next level. This is no good because after finishing, you want to look at your progress and understand what you made. Even worse, if you then click back to the previous level, your progress is gone so you can't review the old solution either. It should require pressing 'Next' to go to the next level, and it should store your solution in local storage or something so you can look back at it.

4) The spring layout of D3 is very distracting when it bounces around rapidly, especially at the start of a level. Could the vertices be initialized to their proper positions? Or, it would be better to hide the canvas for the first couple seconds until the nodes have settled down. 

5) Because the graph is colorful and moving, it draws attention away from the text a lot, which makes it hard to read the text instead of just poking at the graph. If there's important text to read before you start playing, then the graph should only appear after the user has scrolled through the text or pressed a button at the bottom.

**Comment by mrpandey** [comment]
Thank you very very much for your appreciation and your valuable feedback. My goal were both of them. Your suggestions are good and might take some time to think and work upon. Anyway, here's what I have to say.

1. Agreed. In the beginning units, the edges are thin, which get darker and thicker on hovering so that user can click. But since you're facing problems, I guess it needs to be more thicker by default. The later units on walks have thicker edges. Would a similar thickness be okay? Or more?

2. It originally had that select and press 'Del' to remove vertex. But I reworked the entire thing thinking that it would be better if user can do most of the things just by using mouse. At the current moment, I don't really want to go back. But I may change my mind if more people find this unnatural.

3. Total agreement. For the time being, I have increased the timeout from 1000ms to 2500ms (more needed?). I didn't removed the timeout because I think presenting the user with next challenge will keep him engaged. Will add the storage thing later for sure.

4. Well, quite some of my people tell me its cool how the thing jumps into the picture. I am confused about this one.

5. The colorful and moving graph are required to give the user a visual hook. After all it's about visualisation. Text is important too. That's why I chose the layout to fit both the text-area and work-area in a single screen. Because text-only is boring for most, revealing the graphs after reading, would increase the bounce rate.

Again, thank you very much for these suggestions (specially the 3rd one).
